server:
   port: 8080
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/ecomms_db?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false # CHANGE THIS LINE (database name)
      username: admins # CHANGE THIS LINE (username)
      password: root # This matches your desired password, no change needed here
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
         naming:
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
         ddl-auto: update
   servlet:
      multipart:
         enabled: true
         file-size-threshold: 2KB
         max-file-size: 200MB
         max-request-size: 215MB
   http:
      multipart:
         enabled: true
         location: upload
file:
   upload:
      location: ..\upload-dir
logging:
   level:
      com:
         gabriel:
            sbecomms: TRACE # CHANGED THIS LINE - Assuming sbecomms is your backend module